stages:
  - publish

publish:
  stage: publish
  rules:
    # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  image: node:lts-alpine
  script:
    - |
      cat << EOF > .npmrc
      @icons8:registry=$CI_API_V4_URL/packages/npm/
      ${CI_API_V4_URL#https?}/packages/npm/:_authToken=\${CI_JOB_TOKEN}
      EOF
    - npm ci
    - npm run build
    - |
      cat << EOF > .npmrc
      @icons8:registry=$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/npm/
      ${CI_API_V4_URL#https?}/projects/$CI_PROJECT_ID/packages/npm/:_authToken=\${CI_JOB_TOKEN}
      EOF
    - npm publish
